import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
  },
  safeArea: {
    flex: 1,
  },
  glowTop: {
    position: 'absolute',
    top: -120,
    left: -80,
    width: 320,
    height: 320,
    backgroundColor: 'rgba(102,227,255,0.18)',
    borderRadius: 999,
  },
  glowBottom: {
    position: 'absolute',
    bottom: 40,
    right: -80,
    width: 260,
    height: 260,
    backgroundColor: 'rgba(255,200,87,0.14)',
    borderRadius: 999,
  },
  topBar: {
    marginHorizontal: 16,
    marginTop: 8,
    paddingHorizontal: 16,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    borderRadius: 16,
  },
  brand: {
    color: '#f4f7ff',
    fontSize: 22,
    fontFamily: 'Manrope_700Bold',
  },
  profile: {
    color: '#9fb1d1',
    fontSize: 12,
    fontFamily: 'Manrope_400Regular',
  },
  topActions: {
    flexDirection: 'row',
    gap: 10,
  },
  iconButton: {
    width: 44,
    height: 36,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
    backgroundColor: 'rgba(102,227,255,0.1)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconText: {
    color: '#66e3ff',
    fontSize: 12,
    fontFamily: 'Manrope_700Bold',
  },
  ghostButton: {
    height: 36,
    borderRadius: 12,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
    backgroundColor: 'rgba(255,255,255,0.04)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  ghostText: {
    color: '#f4f7ff',
    fontSize: 12,
    fontFamily: 'Manrope_600SemiBold',
  },
  container: {
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 120,
    gap: 18,
  },
  heroRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 10,
  },
  heroText: {
    flex: 1,
  },
  kicker: {
    color: '#66e3ff',
    fontFamily: 'Manrope_600SemiBold',
    letterSpacing: 1,
    fontSize: 12,
    textTransform: 'uppercase',
  },
  pageTitle: {
    color: '#f4f7ff',
    fontSize: 32,
    fontFamily: 'Manrope_700Bold',
  },
  subtitle: {
    color: '#9fb1d1',
    fontSize: 14,
    fontFamily: 'Manrope_400Regular',
  },
  meta: {
    color: '#8fa4c7',
    fontFamily: 'Manrope_400Regular',
    fontSize: 12,
    marginTop: 4,
  },
  heroBadge: {
    backgroundColor: 'rgba(102,227,255,0.12)',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(102,227,255,0.3)',
    alignItems: 'flex-end',
  },
  badgeLabel: {
    color: '#66e3ff',
    fontFamily: 'Manrope_600SemiBold',
    fontSize: 12,
  },
  badgeValue: {
    color: '#f4f7ff',
    fontFamily: 'Manrope_700Bold',
    fontSize: 16,
  },
  heroCard: {
    backgroundColor: 'rgba(255,255,255,0.07)',
    borderRadius: 18,
    padding: 18,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
    gap: 8,
  },
  heroCardLarge: {
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderRadius: 18,
    padding: 18,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
    gap: 12,
  },
  price: {
    color: '#f4f7ff',
    fontSize: 32,
    fontFamily: 'Manrope_700Bold',
  },
  secondaryValue: {
    color: '#e6f0ff',
    fontSize: 18,
    fontFamily: 'Manrope_600SemiBold',
  },
  rowBetween: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  divider: {
    height: 1,
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  pill: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 999,
  },
  pillUp: {
    backgroundColor: 'rgba(111, 245, 175, 0.2)',
  },
  pillDown: {
    backgroundColor: 'rgba(255, 122, 122, 0.2)',
  },
  pillText: {
    color: '#e6f0ff',
    fontFamily: 'Manrope_700Bold',
  },
  statGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  statCard: {
    flexBasis: '48%',
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderWidth: 1,
    borderRadius: 14,
    padding: 12,
  },
  statLabel: {
    color: '#9fb1d1',
    fontFamily: 'Manrope_600SemiBold',
    fontSize: 12,
  },
  statValue: {
    marginTop: 6,
    color: '#eaf7ff',
    fontFamily: 'Manrope_700Bold',
    fontSize: 18,
  },
  quickRow: {
    flexDirection: 'row',
    gap: 10,
  },
  quickCard: {
    flex: 1,
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    borderRadius: 14,
    padding: 14,
    gap: 6,
  },
  quickTitle: {
    color: '#f4f7ff',
    fontFamily: 'Manrope_700Bold',
    fontSize: 14,
  },
  quickSubtitle: {
    color: '#9fb1d1',
    fontFamily: 'Manrope_400Regular',
    fontSize: 12,
  },
  listSection: {
    gap: 12,
  },
  listCard: {
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderColor: 'rgba(255,255,255,0.07)',
    borderWidth: 1,
    borderRadius: 12,
    padding: 12,
    gap: 6,
  },
  listTitle: {
    color: '#f4f7ff',
    fontFamily: 'Manrope_700Bold',
    fontSize: 14,
  },
  listSubtitle: {
    color: '#9fb1d1',
    fontFamily: 'Manrope_400Regular',
    fontSize: 12,
  },
  listValue: {
    color: '#eaf7ff',
    fontFamily: 'Manrope_700Bold',
    fontSize: 16,
  },
  listChange: {
    color: '#66e3ff',
    fontFamily: 'Manrope_600SemiBold',
    fontSize: 12,
  },
  inlineButton: {
    alignSelf: 'flex-start',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 10,
    backgroundColor: 'rgba(102,227,255,0.16)',
    borderWidth: 1,
    borderColor: 'rgba(102,227,255,0.35)',
  },
  inlineText: {
    color: '#d9f6ff',
    fontFamily: 'Manrope_700Bold',
    fontSize: 12,
  },
  commentRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginTop: 8,
  },
  commentInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.18)',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: '#f4f7ff',
    fontFamily: 'Manrope_400Regular',
  },
  commentCard: {
    marginTop: 10,
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    padding: 10,
    gap: 4,
  },
  commentAuthor: {
    color: '#f4f7ff',
    fontFamily: 'Manrope_600SemiBold',
    fontSize: 12,
  },
  commentBody: {
    color: '#cfe2ff',
    fontFamily: 'Manrope_400Regular',
    fontSize: 12,
  },
  commentMeta: {
    marginTop: 8,
    color: '#9fb1d1',
    fontFamily: 'Manrope_400Regular',
    fontSize: 12,
  },
  commentError: {
    marginTop: 8,
    color: '#ffd1d1',
    fontFamily: 'Manrope_600SemiBold',
    fontSize: 12,
  },
  portfolioMessage: {
    marginTop: 8,
    color: '#66e3ff',
    fontFamily: 'Manrope_600SemiBold',
    fontSize: 12,
  },
  errorBox: {
    backgroundColor: 'rgba(255, 122, 122, 0.12)',
    borderColor: 'rgba(255, 122, 122, 0.4)',
    borderWidth: 1,
    borderRadius: 12,
    padding: 12,
  },
  errorText: {
    color: '#ffe1e1',
    fontFamily: 'Manrope_600SemiBold',
  },
  loader: {
    alignItems: 'center',
    paddingVertical: 12,
    gap: 8,
  },
  loadingText: {
    color: '#e6f0ff',
    fontFamily: 'Manrope_600SemiBold',
  },
  toast: {
    backgroundColor: 'rgba(102,227,255,0.14)',
    borderColor: 'rgba(102,227,255,0.28)',
    borderWidth: 1,
    borderRadius: 14,
    padding: 12,
  },
  toastText: {
    color: '#d9f6ff',
    fontFamily: 'Manrope_600SemiBold',
    fontSize: 13,
  },
  authContainer: {
    flexGrow: 1,
    paddingHorizontal: 24,
    paddingTop: 30,
    paddingBottom: 60,
    gap: 18,
    justifyContent: 'center',
  },
  heroTitle: {
    color: '#f4f7ff',
    fontSize: 24,
    fontFamily: 'Manrope_700Bold',
  },
  heroSubtitle: {
    color: '#9fb1d1',
    fontSize: 13,
    fontFamily: 'Manrope_400Regular',
  },
  authCard: {
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderColor: 'rgba(255,255,255,0.12)',
    borderWidth: 1,
    borderRadius: 16,
    padding: 16,
    gap: 10,
  },
  authTitle: {
    color: '#f4f7ff',
    fontSize: 20,
    fontFamily: 'Manrope_700Bold',
  },
  label: {
    color: '#9fb1d1',
    fontFamily: 'Manrope_600SemiBold',
    fontSize: 12,
  },
  input: {
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.18)',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: '#f4f7ff',
    fontFamily: 'Manrope_400Regular',
  },
  primaryButton: {
    backgroundColor: '#66e3ff',
    paddingVertical: 14,
    borderRadius: 14,
    alignItems: 'center',
    marginTop: 4,
  },
  primaryText: {
    color: '#04121f',
    fontFamily: 'Manrope_700Bold',
    fontSize: 16,
  },
  secondaryButton: {
    backgroundColor: 'rgba(12,29,41,0.9)',
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
  },
  secondaryText: {
    color: '#f4f7ff',
    fontFamily: 'Manrope_700Bold',
    fontSize: 14,
  },
  googleButton: {
    backgroundColor: 'rgba(255,255,255,0.08)',
    paddingVertical: 12,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
    alignItems: 'center',
  },
  googleText: {
    color: '#f4f7ff',
    fontFamily: 'Manrope_700Bold',
    fontSize: 14,
  },
  authMessage: {
    color: '#66e3ff',
    fontFamily: 'Manrope_600SemiBold',
    fontSize: 12,
    marginTop: 4,
  },
  profileCard: {
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderColor: 'rgba(255,255,255,0.12)',
    borderWidth: 1,
    borderRadius: 16,
    padding: 16,
    gap: 8,
  },
  profileTitle: {
    color: '#f4f7ff',
    fontFamily: 'Manrope_700Bold',
    fontSize: 18,
  },
  profileLabel: {
    color: '#9fb1d1',
    fontFamily: 'Manrope_600SemiBold',
    fontSize: 12,
  },
  profileValue: {
    color: '#eaf7ff',
    fontFamily: 'Manrope_700Bold',
    fontSize: 14,
  },
  profileMeta: {
    color: '#9fb1d1',
    fontFamily: 'Manrope_400Regular',
    fontSize: 12,
  },
  profileRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 8,
  },
  authLinks: {
    gap: 8,
    alignItems: 'center',
  },
  linkText: {
    color: '#66e3ff',
    fontFamily: 'Manrope_600SemiBold',
    fontSize: 12,
  },
  disabled: {
    opacity: 0.6,
  },
  quantityRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginTop: 8,
  },
  quantityInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.18)',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: '#f4f7ff',
    fontFamily: 'Manrope_400Regular',
  },
});
